stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
    outs:
      - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw
    outs:
      - data/processed
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/processed
    outs:
      - data/interim
      - models/vectorizer
  model_training:
    cmd: python src/models/model_training.py
    deps:
      - src/models/model_training.py
      - data/interim
    outs:
      - models/model
  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
      - src/models/model_evaluation.py
      - models/model
      - models/vectorizer
    outs:
      - models/info
    metrics:
      - reports/metrics.json
  model_registry:
    cmd: python src/models/model_registry.py
    deps:
    - models/info/experiment_info.json
    - src/models/model_registry.py