feature_engineering:
  train_test_split:
    test_size: 0.2
    random_state: 42
  vectorizer:
    max_features: 9000
    ngram_range: [1,1]

model_training:
  LoR:
    penalty: l2
    max_iter: 545
    C: 4.525772411740373
    solver: lbfgs
    n_jobs: -1
  LightGBM:
    max_depth: 4
    n_estimators: 980
    num_leaves: 79
    learning_rate: 0.2377227017601415
    subsample: 0.9774895022351484
    bagging_fraction: 0.6598120738089922
    boosting_type: gbdt
    n_jobs: -1
    objective: multiclass
    verbose: -1
  Meta:
    n_jobs: -1
